version: "3.7"
services:
  postgres:
    image: postgres:16.1-bullseye
    restart: unless-stopped
    volumes:
      - ./target/data/postgres-epicureexpressdb:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_DB=epicureexpressdb
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_HOST_AUTH_METHOD=md5

  application:
    image: epicure-express
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/epicureexpressdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
    - postgres
